"""
FreshMart Publisher
-------------------
Called automatically by runner.py after the agents finish.
Pushes index.html and style.css to a new GitHub branch and opens a PR.

You (the human) review the PR and decide whether to merge to main.
That is the only decision left in the loop.

Environment variables required:
    GITHUB_TOKEN   — personal access token with repo scope
    REPO_PATH      — absolute path to your local FreshMart-Website git clone
                     e.g. /home/pi/FreshMart-Website
"""

import os
import subprocess
from datetime import datetime
from pathlib import Path

import requests


REPO_PATH    = Path(os.environ.get("REPO_PATH", "/home/pi/FreshMart-Website"))
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO  = "hrashid13/FreshMart-Website"
BASE_BRANCH  = "main"


def run(cmd: list, cwd: Path = REPO_PATH) -> str:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(" ".join(cmd) + " failed:\n" + result.stderr)
    return result.stdout.strip()


def main(html: str, css: str, theme: str):
    if not GITHUB_TOKEN:
        raise ValueError("GITHUB_TOKEN environment variable is not set.")
    if not REPO_PATH.exists():
        raise FileNotFoundError("REPO_PATH does not exist: " + str(REPO_PATH))

    # Write files into the local repo clone
    (REPO_PATH / "index.html").write_text(html, encoding="utf-8")
    (REPO_PATH / "style.css").write_text(css, encoding="utf-8")

    # Create a dated branch
    date_str   = datetime.now().strftime("%Y-%m-%d")
    safe_theme = theme.lower().replace(" ", "-").replace("'", "")
    branch     = "weekly-update-" + safe_theme + "-" + datetime.now().strftime("%Y-%m-%d-%H%M")

    run(["git", "checkout", BASE_BRANCH])
    run(["git", "pull", "origin", BASE_BRANCH])
    run(["git", "checkout", "-b", branch])
    run(["git", "add", "index.html", "style.css"])
    run(["git", "commit", "-m", "Weekly ad update - " + theme + " (" + date_str + ")"])
    run([
        "git", "push",
        "https://" + GITHUB_TOKEN + "@github.com/" + GITHUB_REPO + ".git",
        branch,
    ])

    # Open a pull request — you merge it, no one else
    response = requests.post(
        "https://api.github.com/repos/" + GITHUB_REPO + "/pulls",
        headers={
            "Authorization": "token " + GITHUB_TOKEN,
            "Accept": "application/vnd.github.v3+json",
        },
        json={
            "title": "Weekly Ad Update: " + theme + " (" + date_str + ")",
            "body": (
                "Automatically generated by the FreshMart AI agents.\n\n"
                "**Weekly Theme:** " + theme + "\n"
                "**Generated on:** " + date_str + "\n\n"
                "Review and merge to publish to the live site."
            ),
            "head": branch,
            "base": BASE_BRANCH,
        },
    )

    if response.status_code != 201:
        raise RuntimeError(
            "PR creation failed: " + str(response.status_code) + " " + response.text
        )

    pr_url = response.json().get("html_url", "")
    print("Pull request opened: " + pr_url)
    return pr_url


if __name__ == "__main__":
    # Standalone mode (for manual testing)
    from pathlib import Path
    test_html = (Path(__file__).parent / "output" / "index.html").read_text()
    test_css  = (Path(__file__).parent / "output" / "style.css").read_text()
    main(html=test_html, css=test_css, theme="Test Run")
